#!/usr/bin/env bash
# provision-sudoers.sh [--apply]
#
# OPEN-125 / Issue #87 -- idempotent, rejouable provisioning of the ONE scoped sudo
# privilege that makes prepare-persona.sh's controlled entry point possible: letting
# `frappe` (the user Claude Code and the MCP servers run as) trigger a bounded,
# specific renewal WITHOUT gaining a general sudo shell, WITHOUT ever touching
# credentials, and WITHOUT this script itself needing to know a password.
#
# Security posture (mirrors provision-system-identity.sh's discipline exactly):
#   already present AND identical to the generated content -> PASS / no-op
#   already present but DIFFERENT                          -> STOP, never silently
#                                                              overwrite
#   absent                                                  -> create (--apply only;
#                                                              plan-only by default)
#
# The rendered sudoers content is ALWAYS validated with `visudo -c -f <candidate>`
# BEFORE it is ever placed under /etc/sudoers.d/ -- a syntactically broken file dropped
# there can break sudo for the entire host, so this check is not optional and has no
# --skip flag.
#
# Data-driven from personas.yaml (list_enabled_personas.py) -- exactly one NOPASSWD
# rule per currently-enabled persona, naming the exact absolute command
# (`/usr/bin/systemctl start browser-qa-refresh@<persona>.service`), nothing broader:
# no wildcard persona match, no shell, no other systemctl verb, no other unit.
#
# Requires root (sudo) for the --apply path, same as provision-system-identity.sh and
# bootstrap-browser-qa.sh's systemd-install. The read-only PLAN path (rendering the
# candidate and running visudo -c against it) does not require root.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PERSONAS_YAML="${SCRIPT_DIR}/personas.yaml"

# Overridable only for non-destructive testing against a throwaway file owned by the
# test runner itself (see tests/) -- the real deployment always uses the root:root
# defaults below, which is mandatory: a sudoers.d fragment not owned by root is refused
# by sudo entirely, so this is a correctness requirement, not just a convention.
GRANTEE_USER="${PROVISION_SUDOERS_TEST_GRANTEE:-frappe}"
SUDOERS_FILE="${PROVISION_SUDOERS_TEST_FILE:-/etc/sudoers.d/browserqa-prepare-frappe}"
SUDOERS_OWNER="${PROVISION_SUDOERS_TEST_OWNER:-root}"
SUDOERS_GROUP="${PROVISION_SUDOERS_TEST_GROUP:-root}"
SYSTEMCTL_BIN="${PROVISION_SUDOERS_SYSTEMCTL_BIN:-/usr/bin/systemctl}"

apply=0
for arg in "$@"; do
    case "$arg" in
        --apply) apply=1 ;;
        *) echo "provision-sudoers: unknown argument $arg" >&2; exit 2 ;;
    esac
done

log() { echo "provision-sudoers: $*"; }
stop() { echo "provision-sudoers: STOP -- $*" >&2; exit 1; }

render_candidate() {
    local out="$1"
    {
        echo "# Generated by provision-sudoers.sh from personas.yaml (OPEN-125 / Issue #87)."
        echo "# DO NOT HAND-EDIT -- re-run provision-sudoers.sh --apply after changing"
        echo "# personas.yaml instead; a hand edit will be treated as an unexplained"
        echo "# divergence and refused (STOP) on the next run."
        echo "#"
        echo "# Grants ${GRANTEE_USER} exactly one privileged action per enabled persona:"
        echo "# starting that persona's own storageState refresher unit -- nothing else."
        echo "# This is the sole privilege escalation prepare-persona.sh depends on; the"
        echo "# refresher itself (not frappe, not Claude) remains the only reader of real"
        echo "# credentials."
        while IFS= read -r persona; do
            [[ -z "$persona" ]] && continue
            printf '%s ALL=(root) NOPASSWD: %s start browser-qa-refresh@%s.service\n' \
                "$GRANTEE_USER" "$SYSTEMCTL_BIN" "$persona"
        done < <(python3 "${SCRIPT_DIR}/lib/list_enabled_personas.py" --personas "$PERSONAS_YAML")
    } > "$out"
}

CANDIDATE="$(mktemp)"
trap 'rm -f "$CANDIDATE"' EXIT
render_candidate "$CANDIDATE"

if ! visudo -c -f "$CANDIDATE" >/tmp/provision-sudoers.visudo.$$ 2>&1; then
    cat /tmp/provision-sudoers.visudo.$$ >&2
    rm -f /tmp/provision-sudoers.visudo.$$
    stop "generated sudoers content failed 'visudo -c' -- refusing to install anything"
fi
rm -f /tmp/provision-sudoers.visudo.$$
log "generated candidate passes 'visudo -c' syntax validation"

if [[ -f "$SUDOERS_FILE" ]]; then
    if diff -q "$CANDIDATE" "$SUDOERS_FILE" >/dev/null 2>&1; then
        log "'${SUDOERS_FILE}': PASS (already present, matches current personas.yaml)"
        exit 0
    else
        stop "'${SUDOERS_FILE}' already exists but differs from what personas.yaml" \
             "would generate now -- never silently overwritten; review the diff and" \
             "either restore it or re-run with --apply deliberately"
    fi
fi

if [[ "$apply" -eq 1 ]]; then
    install -m 0440 -o "$SUDOERS_OWNER" -g "$SUDOERS_GROUP" "$CANDIDATE" "$SUDOERS_FILE"
    log "'${SUDOERS_FILE}': created (mode 0440, ${SUDOERS_OWNER}:${SUDOERS_GROUP})"
else
    log "'${SUDOERS_FILE}': PLAN -- would create with this content:"
    cat "$CANDIDATE"
fi
