#!/usr/bin/env bash
# provision-sudoers.sh [--apply]
#
# OPEN-125 / Issue #87 -- idempotent, rejouable provisioning of the ONE scoped sudo
# privilege that makes prepare-persona.sh's controlled entry point possible: letting
# `frappe` (the user Claude Code and the MCP servers run as) trigger a bounded,
# specific renewal WITHOUT gaining a general sudo shell, WITHOUT ever touching
# credentials, and WITHOUT this script itself needing to know a password.
#
# Security posture (mirrors provision-system-identity.sh's discipline, extended with a
# controlled update path -- a real gap found by review before merge: refusing EVERY
# divergence, with no update path at all, means adding a persona to personas.yaml and
# re-running --apply -- exactly the documented "add a persona" step 5 -- would STOP
# forever instead of installing the new rule):
#   already present AND identical to the generated content        -> PASS / no-op
#   already present, differs, but recognized as OUR OWN prior      -> UPDATE (--apply
#     output for some past/future personas.yaml (see                only; backed up
#     is_recognized_content below)                                  first)
#   already present, differs, and NOT recognized as ours           -> STOP, never
#     (hand-edited, foreign, or otherwise unexplained)                silently overwrite
#   absent                                                          -> create (--apply
#                                                                       only)
#   (plan-only by default in every case above -- --apply required for any write)
#
# The rendered sudoers content is ALWAYS validated with `visudo -c -f <candidate>`
# BEFORE it is ever placed under /etc/sudoers.d/ -- a syntactically broken file dropped
# there can break sudo for the entire host, so this check is not optional and has no
# --skip flag.
#
# Data-driven from personas.yaml (list_enabled_personas.py) -- exactly one NOPASSWD
# rule per currently-enabled persona, naming the exact absolute command
# (`/usr/bin/systemctl start browser-qa-refresh@<persona>.service`), nothing broader:
# no wildcard persona match, no shell, no other systemctl verb, no other unit.
#
# Requires root (sudo) for the --apply path, same as provision-system-identity.sh and
# bootstrap-browser-qa.sh's systemd-install. The read-only PLAN path (rendering the
# candidate and running visudo -c against it) does not require root.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PERSONAS_YAML="${PROVISION_SUDOERS_TEST_PERSONAS_YAML:-${SCRIPT_DIR}/personas.yaml}"

# Overridable only for non-destructive testing against a throwaway file owned by the
# test runner itself (see tests/) -- the real deployment always uses the root:root
# defaults below, which is mandatory: a sudoers.d fragment not owned by root is refused
# by sudo entirely, so this is a correctness requirement, not just a convention.
GRANTEE_USER="${PROVISION_SUDOERS_TEST_GRANTEE:-frappe}"
SUDOERS_FILE="${PROVISION_SUDOERS_TEST_FILE:-/etc/sudoers.d/browserqa-prepare-frappe}"
SUDOERS_OWNER="${PROVISION_SUDOERS_TEST_OWNER:-root}"
SUDOERS_GROUP="${PROVISION_SUDOERS_TEST_GROUP:-root}"
SYSTEMCTL_BIN="${PROVISION_SUDOERS_SYSTEMCTL_BIN:-/usr/bin/systemctl}"

apply=0
for arg in "$@"; do
    case "$arg" in
        --apply) apply=1 ;;
        *) echo "provision-sudoers: unknown argument $arg" >&2; exit 2 ;;
    esac
done

log() { echo "provision-sudoers: $*"; }
stop() { echo "provision-sudoers: STOP -- $*" >&2; exit 1; }

HEADER_LINES=(
    "# Generated by provision-sudoers.sh from personas.yaml (OPEN-125 / Issue #87)."
    "# DO NOT HAND-EDIT -- re-run provision-sudoers.sh --apply after changing"
    "# personas.yaml instead; a hand edit will be treated as an unexplained"
    "# divergence and refused (STOP) on the next run."
    "#"
    "# Grants ${GRANTEE_USER} exactly one privileged action per enabled persona:"
    "# starting that persona's own storageState refresher unit -- nothing else."
    "# This is the sole privilege escalation prepare-persona.sh depends on; the"
    "# refresher itself (not frappe, not Claude) remains the only reader of real"
    "# credentials."
)
RULE_PREFIX="${GRANTEE_USER} ALL=(root) NOPASSWD: ${SYSTEMCTL_BIN} start browser-qa-refresh@"
RULE_SUFFIX=".service"

render_candidate() {
    local out="$1"
    # Plain command substitution, NOT `done < <(python3 ...)` -- a process substitution's
    # failure is invisible to both `set -e` and this loop (it just sees EOF), found by
    # independent review: personas.yaml transiently unreadable during --apply would
    # silently render zero rules instead of aborting. `x="$(cmd)"` DOES trip `set -e` on
    # a non-zero exit, matching the same call's own convention in bootstrap-browser-qa.sh.
    local personas
    personas="$(python3 "${SCRIPT_DIR}/lib/list_enabled_personas.py" --personas "$PERSONAS_YAML")"
    {
        printf '%s\n' "${HEADER_LINES[@]}"
        while IFS= read -r persona; do
            [[ -z "$persona" ]] && continue
            # Fail closed on anything outside the safe charset -- found by independent
            # review: an unvalidated persona name could contain a sudoers glob character
            # (e.g. "*"), which still passes `visudo -c` (globs are valid syntax) and
            # would silently install a rule broader than the single exact command this
            # design is supposed to guarantee ("jamais wildcard").
            if [[ ! "$persona" =~ ^[A-Za-z0-9_-]+$ ]]; then
                stop "persona name '${persona}' from personas.yaml is not in the safe" \
                    "charset [A-Za-z0-9_-] -- refusing to render a sudoers rule from it"
            fi
            printf '%s%s%s\n' "$RULE_PREFIX" "$persona" "$RULE_SUFFIX"
        done <<< "$personas"
    } > "$out"
}

# A line is a "recognized rule line" if it has exactly our fixed prefix/suffix around a
# syntactically plausible persona name -- deliberately NOT a broad "any NOPASSWD line"
# match, so a tampered rule (e.g. a different command hidden behind a matching-looking
# line) is never silently accepted as "just a persona addition".
is_recognized_rule_line() {
    local line="$1"
    case "$line" in
        "${RULE_PREFIX}"*"${RULE_SUFFIX}") ;;
        *) return 1 ;;
    esac
    local mid="${line#"$RULE_PREFIX"}"
    mid="${mid%"$RULE_SUFFIX"}"
    [[ "$mid" =~ ^[A-Za-z0-9_-]+$ ]]
}

# Recognized as "our own prior (or future) output" if EVERY line is either blank, one of
# our exact fixed header lines, or a recognized rule line -- i.e. the only possible
# difference from what we would generate right now is WHICH personas are listed, which
# is exactly what adding/removing a persona in personas.yaml legitimately changes.
is_recognized_content() {
    local f="$1"
    local line
    while IFS= read -r line || [[ -n "$line" ]]; do
        [[ -z "$line" ]] && continue
        for header_line in "${HEADER_LINES[@]}"; do
            [[ "$line" == "$header_line" ]] && continue 2
        done
        is_recognized_rule_line "$line" && continue
        return 1
    done < "$f"
    return 0
}

CANDIDATE="$(mktemp)"
# MAJOR finding from independent review, fixed: the previous visudo-output capture used
# a predictable `/tmp/provision-sudoers.visudo.$$` path with a plain `>` redirection --
# CWE-59/CWE-377, a classic local symlink pre-plant attack against the root-run --apply
# path (a local user pre-creates a symlink at that path pointing at any root-writable
# file; the redirection follows it, letting root's own write clobber that file). `mktemp`
# (used for CANDIDATE two lines above, and everywhere else write targets are created in
# this repo) creates its file atomically with O_EXCL under a unique, unpredictable name,
# closing that gap entirely -- this is a fix, not just a workaround, since it removes the
# predictable-path precondition the attack needs.
VISUDO_OUTPUT="$(mktemp)"
trap 'rm -f "$CANDIDATE" "$VISUDO_OUTPUT"' EXIT
render_candidate "$CANDIDATE"

if ! visudo -c -f "$CANDIDATE" >"$VISUDO_OUTPUT" 2>&1; then
    cat "$VISUDO_OUTPUT" >&2
    stop "generated sudoers content failed 'visudo -c' -- refusing to install anything"
fi
log "generated candidate passes 'visudo -c' syntax validation"

if [[ -f "$SUDOERS_FILE" ]]; then
    if diff -q "$CANDIDATE" "$SUDOERS_FILE" >/dev/null 2>&1; then
        # Content matching is not the whole contract -- found by independent review:
        # this fast path never re-checked ownership/mode, so a file that drifted to a
        # non-root owner or a wrong mode (sudo silently ignores such a fragment --
        # `#includedir` skips anything not owned/permissioned exactly right) would still
        # report PASS, masking the grant being silently inactive. Same "never silently
        # fix, STOP on real divergence" discipline as everywhere else in this repo --
        # this is a stat check, not a chmod/chown.
        actual_owner_group_mode="$(stat -c '%U:%G:%a' "$SUDOERS_FILE")"
        expected_owner_group_mode="${SUDOERS_OWNER}:${SUDOERS_GROUP}:440"
        if [[ "$actual_owner_group_mode" != "$expected_owner_group_mode" ]]; then
            stop "'${SUDOERS_FILE}' content matches, but ownership/mode is" \
                 "'${actual_owner_group_mode}', expected '${expected_owner_group_mode}'" \
                 "-- never silently re-chmod/chown; investigate before deciding what to do"
        fi
        log "'${SUDOERS_FILE}': PASS (already present, matches current personas.yaml," \
            "ownership/mode conform)"
        exit 0
    fi

    if ! is_recognized_content "$SUDOERS_FILE"; then
        stop "'${SUDOERS_FILE}' already exists but contains content this script did not" \
             "generate (not just a different persona set) -- never silently overwritten;" \
             "review it by hand before deciding what to do"
    fi

    # Recognized as our own prior output, differing only in which personas are listed --
    # a legitimate, expected consequence of editing personas.yaml (adding/removing a
    # persona), not foreign tampering. Controlled update: back up first (same convention
    # as bootstrap-browser-qa.sh's generate-config), then replace.
    old_personas="$(sed -n "s#^${RULE_PREFIX}\\(.*\\)${RULE_SUFFIX}\$#\\1#p" "$SUDOERS_FILE" | sort)"
    new_personas="$(sed -n "s#^${RULE_PREFIX}\\(.*\\)${RULE_SUFFIX}\$#\\1#p" "$CANDIDATE" | sort)"
    added="$(comm -13 <(echo "$old_personas") <(echo "$new_personas"))"
    removed="$(comm -23 <(echo "$old_personas") <(echo "$new_personas"))"

    if [[ "$apply" -eq 0 ]]; then
        log "'${SUDOERS_FILE}': PLAN -- recognized as a prior generation of this exact" \
            "file; would UPDATE (persona set changed -- added: [${added:-none}]," \
            "removed: [${removed:-none}])"
        exit 0
    fi

    backup="${SUDOERS_FILE}.bak.$(date -u +%Y%m%dT%H%M%SZ)"
    cp -p "$SUDOERS_FILE" "$backup"
    log "'${SUDOERS_FILE}': backed up -> ${backup}"
    install -m 0440 -o "$SUDOERS_OWNER" -g "$SUDOERS_GROUP" "$CANDIDATE" "$SUDOERS_FILE"
    log "'${SUDOERS_FILE}': UPDATED (persona set changed -- added: [${added:-none}]," \
        "removed: [${removed:-none}])"
    exit 0
fi

if [[ "$apply" -eq 1 ]]; then
    install -m 0440 -o "$SUDOERS_OWNER" -g "$SUDOERS_GROUP" "$CANDIDATE" "$SUDOERS_FILE"
    log "'${SUDOERS_FILE}': created (mode 0440, ${SUDOERS_OWNER}:${SUDOERS_GROUP})"
else
    log "'${SUDOERS_FILE}': PLAN -- would create with this content:"
    cat "$CANDIDATE"
fi
